<a href="https://colab.research.google.com/github/manowar077/Machine-Learning/blob/main/Panda_For_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

# **1. Create Data Frame**

In [2]:
df=pd.DataFrame([1,2,3,4],columns=['Age'])
print(df)

   Age
0    1
1    2
2    3
3    4

In [3]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [4]:
data={
    'Name':['Manowar','Aahana','Heena','sana'],
    'age':[16,17,18,19],
    'salary':[10000,20000,300000,400000]
}

In [5]:
df=pd.DataFrame(data)
print(df)

      Name  age  salary
0  Manowar   16   10000
1   Aahana   17   20000
2    Heena   18  300000
3     sana   19  400000

Basic Dataframe Understanding

In [6]:
df.head(2)#top data

      Name  age  salary
0  Manowar   16   10000
1   Aahana   17   20000

In [7]:
df.tail(3)

     Name  age  salary
1  Aahana   17   20000
2   Heena   18  300000
3    sana   19  400000

In [8]:
df.shape

(4, 3)

In [9]:
df.columns

Index(['Name', 'age', 'salary'], dtype='object')

In [10]:
df.rename(columns={'salary':'Yearly_salary'},inplace=True)

In [11]:
df

      Name  age  Yearly_salary
0  Manowar   16          10000
1   Aahana   17          20000
2    Heena   18         300000
3     sana   19         400000

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Name           4 non-null      object
 1   age            4 non-null      int64
 2   Yearly_salary  4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes

In [13]:
df.describe()

             age  Yearly_salary
count   4.000000       4.000000
mean   17.500000  182500.000000
std     1.290994  197716.126471
min    16.000000   10000.000000
25%    16.750000   17500.000000
50%    17.500000  160000.000000
75%    18.250000  325000.000000
max    19.000000  400000.000000

In [14]:
  #3.Save and Load data from csv

In [15]:
df.to_csv('data.csv',index=False)

In [16]:
load_df=pd.read_csv('data.csv')

In [17]:
load_df

      Name  age  Yearly_salary
0  Manowar   16          10000
1   Aahana   17          20000
2    Heena   18         300000
3     sana   19         400000

**4.Rows and column -> selection**

In [18]:
#select column
df[['Name','Yearly_salary']] #single column Extract

      Name  Yearly_salary
0  Manowar          10000
1   Aahana          20000
2    Heena         300000
3     sana         400000

In [19]:
#select rows
df.loc[df.Name=='Manowar'] #loc-> labbled based indexing

      Name  age  Yearly_salary
0  Manowar   16          10000

In [20]:
#condition
df.loc[(df.Name=='Manowar')&(df.Yearly_salary>=5000)]

      Name  age  Yearly_salary
0  Manowar   16          10000

iloc -index-value based

In [21]:
df.iloc[0] #iloc-> index based indexing
df.iloc[0:2]

      Name  age  Yearly_salary
0  Manowar   16          10000
1   Aahana   17          20000

**5.Filter DataFrame**

In [22]:
df

      Name  age  Yearly_salary
0  Manowar   16          10000
1   Aahana   17          20000
2    Heena   18         300000
3     sana   19         400000

In [23]:
df[df['age']>18]

   Name  age  Yearly_salary
3  sana   19         400000

In [24]:
df[(df['age']>=2) & (df['Yearly_salary']>=5000)]

      Name  age  Yearly_salary
0  Manowar   16          10000
1   Aahana   17          20000
2    Heena   18         300000
3     sana   19         400000

**6.Operation On Column and Row**

In [25]:
df

      Name  age  Yearly_salary
0  Manowar   16          10000
1   Aahana   17          20000
2    Heena   18         300000
3     sana   19         400000

In [26]:
#add A new column
df['Team']=['CEO','HR','CTO','DA']
df

      Name  age  Yearly_salary Team
0  Manowar   16          10000  CEO
1   Aahana   17          20000   HR
2    Heena   18         300000  CTO
3     sana   19         400000   DA

In [27]:
df['Yearly_salary']=[10000,12000,13000,14000]

In [28]:
df['Name']=['Manowar','Arkam','Aahana','khusee']

In [29]:
df['Bonus']=df['Yearly_salary']*0.2
df

      Name  age  Yearly_salary Team   Bonus
0  Manowar   16          10000  CEO  2000.0
1    Arkam   17          12000   HR  2400.0
2   Aahana   18          13000  CTO  2600.0
3   khusee   19          14000   DA  2800.0

In [30]:
#Adding new rows
df.loc[len(df)]=['Huzaifa', 21, 14000, 'IT', 3000.0]

In [31]:
df

      Name  age  Yearly_salary Team   Bonus
0  Manowar   16          10000  CEO  2000.0
1    Arkam   17          12000   HR  2400.0
2   Aahana   18          13000  CTO  2600.0
3   khusee   19          14000   DA  2800.0
4  Huzaifa   21          14000   IT  3000.0

In [32]:
len(df)

5

In [33]:
#update value
df.loc[0,'age']=22

In [34]:
df

      Name  age  Yearly_salary Team   Bonus
0  Manowar   22          10000  CEO  2000.0
1    Arkam   17          12000   HR  2400.0
2   Aahana   18          13000  CTO  2600.0
3   khusee   19          14000   DA  2800.0
4  Huzaifa   21          14000   IT  3000.0

In [35]:
#delete value
#column drop
df.drop('Bonus',axis=1)

      Name  age  Yearly_salary Team
0  Manowar   22          10000  CEO
1    Arkam   17          12000   HR
2   Aahana   18          13000  CTO
3   khusee   19          14000   DA
4  Huzaifa   21          14000   IT

In [36]:
#row drop
df.drop(df[df.Name=='Aahana'].index)

      Name  age  Yearly_salary Team   Bonus
0  Manowar   22          10000  CEO  2000.0
1    Arkam   17          12000   HR  2400.0
3   khusee   19          14000   DA  2800.0
4  Huzaifa   21          14000   IT  3000.0

In [37]:
#sort values
df.sort_values('Yearly_salary',ascending=False)

      Name  age  Yearly_salary Team   Bonus
4  Huzaifa   21          14000   IT  3000.0
3   khusee   19          14000   DA  2800.0
2   Aahana   18          13000  CTO  2600.0
1    Arkam   17          12000   HR  2400.0
0  Manowar   22          10000  CEO  2000.0

**&.Working With Date Value**

In [38]:
# add date time column
df['D_O_J']=['01-01-2020','02-02-2021','03-03-2022','04-04-2023','05-05-2024']

In [39]:
df

      Name  age  Yearly_salary Team   Bonus       D_O_J
0  Manowar   22          10000  CEO  2000.0  01-01-2020
1    Arkam   17          12000   HR  2400.0  02-02-2021
2   Aahana   18          13000  CTO  2600.0  03-03-2022
3   khusee   19          14000   DA  2800.0  04-04-2023
4  Huzaifa   21          14000   IT  3000.0  05-05-2024

In [40]:
df['D_O_J'].dtype

dtype('O')

In [41]:
df['D_O_J']=pd.to_datetime(df['D_O_J'],format='%d-%m-%Y')

In [42]:
df

      Name  age  Yearly_salary Team   Bonus      D_O_J
0  Manowar   22          10000  CEO  2000.0 2020-01-01
1    Arkam   17          12000   HR  2400.0 2021-02-02
2   Aahana   18          13000  CTO  2600.0 2022-03-03
3   khusee   19          14000   DA  2800.0 2023-04-04
4  Huzaifa   21          14000   IT  3000.0 2024-05-05

In [43]:
df['D_O_J'].dt.year

0    2020
1    2021
2    2022
3    2023
4    2024
Name: D_O_J, dtype: int32

In [44]:
df['D_O_J'].dt.month

0    1
1    2
2    3
3    4
4    5
Name: D_O_J, dtype: int32

In [45]:
df['D_O_J'].dt.day

0    1
1    2
2    3
3    4
4    5
Name: D_O_J, dtype: int32

In [46]:
display(df['D_O_J'].dt.day_name())

0    Wednesday
1      Tuesday
2     Thursday
3      Tuesday
4       Sunday
Name: D_O_J, dtype: object

In [47]:
df['Month']=df['D_O_J'].dt.month

In [48]:
df

      Name  age  Yearly_salary Team   Bonus      D_O_J  Month
0  Manowar   22          10000  CEO  2000.0 2020-01-01      1
1    Arkam   17          12000   HR  2400.0 2021-02-02      2
2   Aahana   18          13000  CTO  2600.0 2022-03-03      3
3   khusee   19          14000   DA  2800.0 2023-04-04      4
4  Huzaifa   21          14000   IT  3000.0 2024-05-05      5

In [49]:
df['D_O_J']+pd.Timedelta(days=90)

0   2020-03-31
1   2021-05-03
2   2022-06-01
3   2023-07-03
4   2024-08-03
Name: D_O_J, dtype: datetime64[ns]

**8.Handaling MIssing Value**

In [50]:
df.isnull()

    Name    age  Yearly_salary   Team  Bonus  D_O_J  Month
0  False  False          False  False  False  False  False
1  False  False          False  False  False  False  False
2  False  False          False  False  False  False  False
3  False  False          False  False  False  False  False
4  False  False          False  False  False  False  False

In [51]:
import numpy as np

In [52]:
df.loc[df.Name=='Manowar','yearly_salary']=np.nan

In [53]:
df

      Name  age  Yearly_salary Team   Bonus      D_O_J  Month  yearly_salary
0  Manowar   22          10000  CEO  2000.0 2020-01-01      1            NaN
1    Arkam   17          12000   HR  2400.0 2021-02-02      2            NaN
2   Aahana   18          13000  CTO  2600.0 2022-03-03      3            NaN
3   khusee   19          14000   DA  2800.0 2023-04-04      4            NaN
4  Huzaifa   21          14000   IT  3000.0 2024-05-05      5            NaN

In [54]:
df.fillna(0)

      Name  age  Yearly_salary Team   Bonus      D_O_J  Month  yearly_salary
0  Manowar   22          10000  CEO  2000.0 2020-01-01      1            0.0
1    Arkam   17          12000   HR  2400.0 2021-02-02      2            0.0
2   Aahana   18          13000  CTO  2600.0 2022-03-03      3            0.0
3   khusee   19          14000   DA  2800.0 2023-04-04      4            0.0
4  Huzaifa   21          14000   IT  3000.0 2024-05-05      5            0.0

In [55]:
df

      Name  age  Yearly_salary Team   Bonus      D_O_J  Month  yearly_salary
0  Manowar   22          10000  CEO  2000.0 2020-01-01      1            NaN
1    Arkam   17          12000   HR  2400.0 2021-02-02      2            NaN
2   Aahana   18          13000  CTO  2600.0 2022-03-03      3            NaN
3   khusee   19          14000   DA  2800.0 2023-04-04      4            NaN
4  Huzaifa   21          14000   IT  3000.0 2024-05-05      5            NaN

**9.Aggregation and groupBy**

In [56]:
df['Team'].value_counts()

Team
CEO    1
HR     1
CTO    1
DA     1
IT     1
Name: count, dtype: int64

In [57]:
#Group By
df.groupby('Month')['Yearly_salary']

In [58]:
df

      Name  age  Yearly_salary Team   Bonus      D_O_J  Month  yearly_salary
0  Manowar   22          10000  CEO  2000.0 2020-01-01      1            NaN
1    Arkam   17          12000   HR  2400.0 2021-02-02      2            NaN
2   Aahana   18          13000  CTO  2600.0 2022-03-03      3            NaN
3   khusee   19          14000   DA  2800.0 2023-04-04      4            NaN
4  Huzaifa   21          14000   IT  3000.0 2024-05-05      5            NaN

In [59]:
df.groupby('Month')['Yearly_salary'].sum() #aggregation based on group by

Month
1    10000
2    12000
3    13000
4    14000
5    14000
Name: Yearly_salary, dtype: int64

In [66]:
df.groupby('Month').agg({'Yearly_salary':'mean','Name':'count'})

       Yearly_salary  Name
Month
1            10000.0     1
2            12000.0     1
3            13000.0     1
4            14000.0     1
5            14000.0     1

**10.concatinate and Merge data frame (Joins)**

In [64]:
df1=pd.DataFrame({'Id':[1,2,3],'Name':['Manowar','Arkam','Aahana']})

In [65]:
df2=pd.DataFrame({'Id':[1,2,3,4],'Score':[88,34,56,76]})

In [ ]:
#join